line-length = 120
output-format = "grouped"
show-fixes = true
target-version = "py311"

[format]
docstring-code-format = true
indent-style = "tab"
line-ending = "lf"
quote-style = "single"

[lint]
select = [
	"I001", # Import block is un-sorted or un-formatted
	"I002", # Missing required import: {name}
	"W505", # pycodestyle -> Warning -> "Doc line too long"
]

[lint.pycodestyle]
max-doc-length = 120
